### ISSUE TITLE
Issue with S3 Permissions JSON

### ISSUE THREAD

**Issue by alexmal98** [NetAppDocs/bluexp-backup-recovery#208]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html#set-up-s3-permissions

### Page title

Back up on-premises ONTAP data to Amazon S3

### Summary

Under Set up S3 permissions, in Step 1, under Details, you can see the JSON code.  It is cut off though, missing quite a bit of the code.  If you compare step 1 details with step 2 you'll see the first part is missing.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
(This issue was originally opened in the bluexp-setup-admin repo.)

I discussed the issue with Alex. My summary of the issue is as follows.

In the step, only a subset of the Connector policy permissions appears. The purpose is to say that the Connector policy should include the listed permissions, which enable backup to S3. But the Connector policy itself contains much more than just these permissions. That's a confusing.

Instead, the step should simply state that you should ensure that the Connector has the required permissions and point to the setup-admin docs: https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html

**Comment by amgrissino** [comment]
@netapp-bcammett  - Looks like you're referring to Step 1 under Prepare Amazon S3 as your backup target > Set up S3 permissions. And, that Step 1 should be revised to ensure that the Connector has the required perms and point to setup-admin docs. It wasn't quite clear which step you were referring to, but I assume it's Step 1.

**Comment by amgrissino** [comment]
Pushing out changes today.
